### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by TsunokakeTaiki** [TsunokakeTaiki/protospace-31694#1]
#URL
https://protospace-31694.herokuapp.com/

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]

- [x] 各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移するようにしましょう！
現在、一部のユーザー名をクリックするとエラーになります
<img width="239" alt="ProtoSpace" src="https://user-images.githubusercontent.com/49669977/99343140-a1ee7500-28d0-11eb-949d-93cf124d5599.png">

修正が完了しましたら、以下のprotospace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by TsunokakeTaiki** [comment]
コメント欄のユーザーリンクを修正しました。
ご確認よろしくお願いします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルにお送りいたします。
今しばらくお待ちください。
